x-environment-variables: &environment-variables
  CERTS_ConnectionStrings__Default: Data Source=/app/data/certs.db
  CERTS_AcmeStore__Directory: /app/data/acme_store
x-certs-volumes: &certs-volumes
  - certs-data:/app/data

name: certs_center_dev

volumes:
  certs-data:
    name: certs-data-dev

services:
  migrations:
    container_name: migrations
    image: localhost/certs_cli:latest
    volumes: *certs-volumes
    environment: 
      <<: *environment-variables
    # entrypoint: ["dotnet", "cli.dll"]
    command: ["database", "update"]
    restart: on-failure:3
  web:
    container_name: certs_web
    image: localhost/certs_server:latest
    volumes: *certs-volumes
    environment: 
      <<: *environment-variables
      CERTS_Serilog__WriteTo__0__Args__outputTemplete: '{Level:u3} {Timestamp:HH:mm:ss} {Message:lj}{NewLine}{Exception}'
      CERTS_Acme__Email__0: use@your.email
      CERTS_Acme__AcceptTermOfService: true
      CERTS_AlibabaCloud__AccessKeyId: youraccesskeyid
      CERTS_AlibabaCloud__AccessKeySecret: youraccesskeysecret
      CERTS_AlibebeCloud__Address: alidns.cn-hangzhou.aliyuncs.com
      CERTS_EnableSwagger: true
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: on-failure:3
    network_mode: host
    ports:
      - 8765:8080

