// <auto-generated />
using System;
using CertsServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CertsServer.Migrations
{
    [DbContext(typeof(CertsServerDbContext))]
    [Migration("20250803092454_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114");

            modelBuilder.Entity("CertsServer.Data.TicketCertificateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NotAfter")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NotBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TicketEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketEntityId");

                    b.ToTable("ticket_certificates", (string)null);
                });

            modelBuilder.Entity("CertsServer.Data.TicketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("PfxPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("CertsServer.Data.TicketCertificateEntity", b =>
                {
                    b.HasOne("CertsServer.Data.TicketEntity", null)
                        .WithMany("Certificates")
                        .HasForeignKey("TicketEntityId");
                });

            modelBuilder.Entity("CertsServer.Data.TicketEntity", b =>
                {
                    b.Navigation("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
